CREATE OR ALTER PROCEDURE SP_INSERTAR_USUARIO_ROL
    @ID_USUARIO INT,
    @ID_TIPO_USUARIO INT
AS
BEGIN
    -- Evitar duplicados
    IF NOT EXISTS (
        SELECT 1 FROM MAE_USUARIO_ROL
        WHERE ID_USUARIO = @ID_USUARIO AND ID_TIPO_USUARIO = @ID_TIPO_USUARIO
    )
    BEGIN
        INSERT INTO MAE_USUARIO_ROL (ID_USUARIO, ID_TIPO_USUARIO)
        VALUES (@ID_USUARIO, @ID_TIPO_USUARIO);
    END

    -- Si el rol es "Comité" (ID = 6), actualizamos la tabla MAE_USUARIO
    IF @ID_TIPO_USUARIO = 6
    BEGIN
        UPDATE MAE_USUARIO
        SET COMITE = 1
        WHERE ID_USUARIO = @ID_USUARIO;
    END
END;
GO
