CREATE PROCEDURE SP_INSERTAR_USUARIO_ROL
    @ID_USUARIO INT,
    @ID_TIPO_USUARIO INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM MAE_USUARIO_ROL
        WHERE ID_USUARIO = @ID_USUARIO AND ID_TIPO_USUARIO = @ID_TIPO_USUARIO
    )
    BEGIN
        INSERT INTO MAE_USUARIO_ROL (ID_USUARIO, ID_TIPO_USUARIO)
        VALUES (@ID_USUARIO, @ID_TIPO_USUARIO);
    END
END;
GO
