CREATE OR ALTER PROCEDURE SP_ELIMINAR_USUARIO_ROL
    @ID_USUARIO INT,
    @ID_TIPO_USUARIO INT
AS
BEGIN
    DELETE FROM MAE_USUARIO_ROL
    WHERE ID_USUARIO = @ID_USUARIO AND ID_TIPO_USUARIO = @ID_TIPO_USUARIO;

    -- Si quitamos el rol Comité (ID = 6), actualizamos la tabla MAE_USUARIO
    IF @ID_TIPO_USUARIO = 6
    BEGIN
        UPDATE MAE_USUARIO
        SET COMITE = 0
        WHERE ID_USUARIO = @ID_USUARIO;
    END
END;
GO


--Eliminar rol usuario con ID
--EXEC SP_ELIMINAR_USUARIO_ROL @ID_USUARIO = 5, @ID_TIPO_USUARIO = 1;