CREATE PROCEDURE SP_ELIMINAR_USUARIO_ROL
    @ID_USUARIO INT,
    @ID_TIPO_USUARIO INT
AS
BEGIN
    DELETE FROM MAE_USUARIO_ROL
    WHERE ID_USUARIO = @ID_USUARIO AND ID_TIPO_USUARIO = @ID_TIPO_USUARIO;
END;
GO

--Eliminar rol usuario con ID
--EXEC SP_ELIMINAR_USUARIO_ROL @ID_USUARIO = 5, @ID_TIPO_USUARIO = 1;