CREATE OR ALTER PROCEDURE SP_LISTAR_ROLES_POR_USUARIO
    @ID_USUARIO INT
AS
BEGIN
    -- Rol principal
    SELECT u.ID_USUARIO, tu.ID_TIPO_USUARIO, tu.DETALLE_USUARIO, 'Principal' AS ORIGEN
    FROM MAE_USUARIO u
    JOIN MAE_TIPO_USUARIO tu ON u.ID_TIPO_USUARIO = tu.ID_TIPO_USUARIO
    WHERE u.ID_USUARIO = @ID_USUARIO

    UNION

    -- Roles adicionales
    SELECT r.ID_USUARIO, tu.ID_TIPO_USUARIO, tu.DETALLE_USUARIO, 'Adicional' AS ORIGEN
    FROM MAE_USUARIO_ROL r
    JOIN MAE_TIPO_USUARIO tu ON r.ID_TIPO_USUARIO = tu.ID_TIPO_USUARIO
    WHERE r.ID_USUARIO = @ID_USUARIO;
END;
GO

--EXEC SP_LISTAR_ROLES_POR_USUARIO @ID_USUARIO = 4;
