ALTER PROCEDURE SP_INSERTAR_ROL_MENU
    @ID_ROL INT,
    @ID_MENU INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM MAE_ROL_MENU
        WHERE ID_ROL = @ID_ROL AND ID_MENU = @ID_MENU
    )
    BEGIN
        INSERT INTO MAE_ROL_MENU (ID_ROL, ID_MENU)
        VALUES (@ID_ROL, @ID_MENU);
    END
END;
GO