ALTER PROCEDURE SP_INSERTAR_ROL_SUBMENU
    @ID_ROL INT,
    @ID_SUBMENU INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM MAE_ROL_SUBMENU
        WHERE ID_ROL = @ID_ROL AND ID_SUBMENU = @ID_SUBMENU
    )
    BEGIN
        INSERT INTO MAE_ROL_SUBMENU (ID_ROL, ID_SUBMENU)
        VALUES (@ID_ROL, @ID_SUBMENU);
    END
END;
GO