CREATE OR ALTER PROCEDURE SP_OBTENER_MENUS_Y_SUBMENUS
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        M.ID_MENU,
        M.NOMBRE AS MENU_NOMBRE,
        M.ICONO AS MENU_ICONO,
        M.URL AS MENU_URL,
        M.ORDEN AS MENU_ORDEN,
        SM.ID_SUBMENU,
        SM.NOMBRE AS SUBMENU_NOMBRE,
        SM.ICONO AS SUBMENU_ICONO,
        SM.URL AS SUBMENU_URL,
        SM.ORDEN AS SUBMENU_ORDEN
    FROM MAE_MENU M
    LEFT JOIN MAE_SUBMENU SM ON SM.ID_MENU = M.ID_MENU AND SM.ESTADO = 1
    WHERE M.ESTADO = 1
    ORDER BY M.ORDEN, SM.ORDEN;
END;
GO
