-- SP_ACTUALIZAR_MENU
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_MENU
    @ID_MENU INT,
    @NOMBRE VARCHAR(50),
    @ICONO VARCHAR(50),
    @URL VARCHAR(100) = NULL
AS
BEGIN
    UPDATE MAE_MENU
    SET NOMBRE = @NOMBRE,
        ICONO = @ICONO,
        URL = @URL
    WHERE ID_MENU = @ID_MENU AND ESTADO = 1;
END;
GO