-- 🏷 Tabla MAE_TIPO_USUARIO (User Types)
CREATE TABLE dbo.MAE_TIPO_USUARIO
(
    ID_TIPO_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    DETALLE_USUARIO VARCHAR(20) NOT NULL UNIQUE,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)) -- 0 = Inactivo, 1 = Activo
);
GO

-- 🏷 Tabla MAE_SEXO (Gender)
CREATE TABLE dbo.MAE_SEXO
(
    ID_SEXO INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPCION VARCHAR(10) NOT NULL UNIQUE CHECK (DESCRIPCION IN ('Masculino', 'Femenino'))
);
GO

-- 👤 Tabla MAE_USUARIO (Users/Residents)
CREATE TABLE dbo.MAE_USUARIO
(
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DNI VARCHAR(12) NOT NULL UNIQUE,
    CORREO VARCHAR(100) NULL,
    CELULAR VARCHAR(9) UNIQUE CHECK (CELULAR LIKE '[9]________'),
    CONTACTO_EMERGENCIA VARCHAR(9) CHECK (CONTACTO_EMERGENCIA LIKE '[9]________'),
    FECHA_NACIMIENTO DATE,
    ID_TIPO_USUARIO INT NOT NULL,
    ID_SEXO INT NOT NULL,
    DETALLE VARCHAR(100),
    OBSERVACIONES VARCHAR(200),
    COMITE BIT NOT NULL CHECK (COMITE IN (0, 1)), -- 0 = No, 1 = Sí
    USUARIO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA_HASH VARCHAR(255) NOT NULL,  
    CONTRASENA_SALT VARCHAR(50) NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_USUARIO_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO),
    CONSTRAINT FK_USUARIO_SEXO FOREIGN KEY (ID_SEXO) REFERENCES MAE_SEXO(ID_SEXO)
);
GO

ALTER TABLE MAE_USUARIO
ADD PRIMER_INICIO BIT NOT NULL DEFAULT 1;

-- 🐶 Tabla MAE_MASCOTA (Pets)
CREATE TABLE dbo.MAE_MASCOTA
(
    ID_MASCOTA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('Perro', 'Gato', 'Ave', 'Otro')),
    RAZA VARCHAR(50),
    EDAD INT CHECK (EDAD >= 0),
    DNI_DUENO VARCHAR(12) NOT NULL,

    -- Clave foránea
    CONSTRAINT FK_MASCOTA_USUARIO FOREIGN KEY (DNI_DUENO) REFERENCES MAE_USUARIO(DNI) ON DELETE CASCADE
);
GO

-- 📂 Tabla MAE_MENU (Main Menus)
CREATE TABLE dbo.MAE_MENU
(
    ID_MENU INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    ICONO VARCHAR(50) NULL,
    URL VARCHAR(100) NULL,
    ORDEN INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1))
);
GO

-- 📂 Tabla MAE_SUBMENU (Submenus)
CREATE TABLE dbo.MAE_SUBMENU
(
    ID_SUBMENU INT IDENTITY(1,1) PRIMARY KEY,
    ID_MENU INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    ICONO VARCHAR(50) NULL,
    URL VARCHAR(100) NOT NULL,
    ORDEN INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_SUBMENU_MENU FOREIGN KEY (ID_MENU) REFERENCES MAE_MENU(ID_MENU) ON DELETE CASCADE
);
GO

-- 🔐 Tabla MAE_ROL_MENU (Menu Permissions by User Type)
CREATE TABLE dbo.MAE_ROL_MENU
(
    ID_TIPO_USUARIO INT NOT NULL,
    ID_MENU INT NOT NULL,

    CONSTRAINT FK_ROL_MENU_TIPO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_ROL_MENU_MENU FOREIGN KEY (ID_MENU) REFERENCES MAE_MENU(ID_MENU) ON DELETE CASCADE
);
GO

-- 🔐 Tabla MAE_ROL_SUBMENU (Submenu Permissions by User Type)
CREATE TABLE dbo.MAE_ROL_SUBMENU
(
    ID_TIPO_USUARIO INT NOT NULL,
    ID_SUBMENU INT NOT NULL,

    CONSTRAINT FK_ROL_SUBMENU_TIPO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_ROL_SUBMENU_SUBMENU FOREIGN KEY (ID_SUBMENU) REFERENCES MAE_SUBMENU(ID_SUBMENU) ON DELETE CASCADE
);
GO

CREATE TABLE dbo.MAE_USUARIO_ROL (
    ID_USUARIO INT NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,

    CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID_USUARIO, ID_TIPO_USUARIO),
    CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_ROL_TIPO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE
);
GO

CREATE INDEX IDX_MAE_ROL_MENU_TIPO ON MAE_ROL_MENU(ID_TIPO_USUARIO, ID_MENU);
CREATE INDEX IDX_MAE_ROL_SUBMENU_TIPO ON MAE_ROL_SUBMENU(ID_TIPO_USUARIO, ID_SUBMENU);

-- 🏢 Tabla MAE_PROPIETARIO  --NO USO ESTA TABLA ACTUALMENTE
CREATE TABLE dbo.MAE_PROPIETARIO
(
    ID_PROPIETARIO INT IDENTITY(1,1) PRIMARY KEY,
    DNI VARCHAR(12) NOT NULL,
    NRO_DPTO INT NOT NULL,
    FECHA_INICIO_PROPIEDAD DATE NOT NULL,
    FECHA_FIN_PROPIEDAD DATE NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_PROPIETARIO_USUARIO FOREIGN KEY (DNI) REFERENCES MAE_USUARIO(DNI) ON DELETE CASCADE,
    CONSTRAINT CHK_FECHA_PROPIEDAD CHECK (FECHA_FIN_PROPIEDAD IS NULL OR FECHA_FIN_PROPIEDAD > FECHA_INICIO_PROPIEDAD)
);
GO

-- 📜 Tabla MAE_DOCUMENTO_ADMIN (Administrative Documents)
CREATE TABLE dbo.MAE_DOCUMENTO_ADMIN
(
    ID_DOCUMENTO INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    TIPO_DOCUMENTO VARCHAR(50) NOT NULL CHECK (TIPO_DOCUMENTO IN ('Reglamento', 'Contrato', 'Informe', 'Otro')),
    RUTA_ARCHIVO VARCHAR(255) NOT NULL,
    FECHA_SUBIDA DATE NOT NULL DEFAULT GETDATE(),
    ID_USUARIO_SUBIDA INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_DOCUMENTO_USUARIO FOREIGN KEY (ID_USUARIO_SUBIDA) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- 🚪 Tabla MAE_VISITA (Visits)
CREATE TABLE dbo.MAE_VISITA
(
    ID_VISITA INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    NOMBRE_VISITANTE VARCHAR(100) NOT NULL,
    DNI_VISITANTE VARCHAR(12) NOT NULL,
    FECHA_INGRESO DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_SALIDA DATETIME NULL,
    MOTIVO VARCHAR(100) NULL,
    ID_USUARIO_REGISTRO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_VISITA_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_VISITA CHECK (FECHA_SALIDA IS NULL OR FECHA_SALIDA > FECHA_INGRESO)
);
GO
-- Crear la tabla con la restricción ajustada
CREATE TABLE dbo.MAE_VISITA_PROGRAMADA
(
    ID_VISITA_PROGRAMADA INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    NOMBRE_VISITANTE VARCHAR(100) NOT NULL CHECK (LEN(TRIM(NOMBRE_VISITANTE)) > 0),
    DNI_VISITANTE VARCHAR(12) NOT NULL CHECK (LEN(TRIM(DNI_VISITANTE)) >= 8),
    FECHA_LLEGADA DATE NOT NULL,
    HORA_LLEGADA TIME NULL,
    MOTIVO VARCHAR(100) NOT NULL CHECK (LEN(TRIM(MOTIVO)) > 0),
    ID_USUARIO_PROPIETARIO INT NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT GETDATE(),
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),
    CONSTRAINT FK_VISITA_PROG_USUARIO_PROPIETARIO 
        FOREIGN KEY (ID_USUARIO_PROPIETARIO) 
        REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_LLEGADA 
        CHECK (FECHA_LLEGADA >= CAST(DATEADD(HOUR, -5, GETDATE()) AS DATE)),
    CONSTRAINT CHK_DNI_VISITANTE 
        CHECK (DNI_VISITANTE NOT LIKE '%[^a-zA-Z0-9]%')
);

-- Crear índice no agrupado para optimizar consultas por FECHA_LLEGADA y ESTADO
CREATE NONCLUSTERED INDEX IX_MAE_VISITA_PROGRAMADA_FECHA_ESTADO
ON dbo.MAE_VISITA_PROGRAMADA (FECHA_LLEGADA, ESTADO);

-- 🔧 Tabla MAE_PROVEEDOR (Suppliers)
CREATE TABLE dbo.MAE_PROVEEDOR
(
    ID_PROVEEDOR INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    RUC VARCHAR(11) NOT NULL UNIQUE CHECK (RUC LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    TELEFONO VARCHAR(9) NULL CHECK (TELEFONO LIKE '[9]________'),
    CORREO VARCHAR(100) NULL,
    TIPO_SERVICIO VARCHAR(50) NOT NULL CHECK (TIPO_SERVICIO IN ('Mantenimiento', 'Limpieza', 'Seguridad', 'Otro')),
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1))
);
GO

-- 🔧 Tabla MAE_MANTENIMIENTO (Maintenance by Suppliers)
CREATE TABLE dbo.MAE_MANTENIMIENTO
(
    ID_MANTENIMIENTO INT IDENTITY(1,1) PRIMARY KEY,
    ID_PROVEEDOR INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA_MANTENIMIENTO DATE NOT NULL,
    COSTO DECIMAL(10, 2) NOT NULL CHECK (COSTO >= 0),
    NRO_DPTO INT NULL,
    ID_USUARIO_REGISTRO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_MANTENIMIENTO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES MAE_PROVEEDOR(ID_PROVEEDOR) ON DELETE NO ACTION,
    CONSTRAINT FK_MANTENIMIENTO_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- 📦 Tabla MAE_ENCARGO (Packages/Deliveries)
CREATE TABLE dbo.MAE_ENCARGO
(
    ID_ENCARGO INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA_RECEPCION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ENTREGA DATETIME NULL,
    ID_USUARIO_RECEPCION INT NOT NULL,
    ID_USUARIO_ENTREGA INT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_ENCARGO_USUARIO_RECEPCION FOREIGN KEY (ID_USUARIO_RECEPCION) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT FK_ENCARGO_USUARIO_ENTREGA FOREIGN KEY (ID_USUARIO_ENTREGA) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_ENCARGO CHECK (FECHA_ENTREGA IS NULL OR FECHA_ENTREGA > FECHA_RECEPCION)
);
GO

-- 💸 Tabla MAE_DEUDOR 
CREATE TABLE dbo.MAE_DEUDOR
(
    ID_DEUDA INT IDENTITY(1,1) PRIMARY KEY,
    DNI VARCHAR(12) NOT NULL,
    NRO_DPTO INT NOT NULL,
    MONTO DECIMAL(10, 2) NOT NULL CHECK (MONTO > 0),
    FECHA_VENCIMIENTO DATE NOT NULL,
    FECHA_PAGO DATE NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_DEUDOR_USUARIO FOREIGN KEY (DNI) REFERENCES MAE_USUARIO(DNI) ON DELETE CASCADE,
    CONSTRAINT CHK_FECHA_PAGO CHECK (FECHA_PAGO IS NULL OR FECHA_PAGO >= FECHA_VENCIMIENTO)
);
GO

-- 📅 Tabla MAE_RESERVA (Reservations)
CREATE TABLE dbo.MAE_RESERVA
(
    ID_RESERVA INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    TIPO_AREA VARCHAR(50) NOT NULL CHECK (TIPO_AREA IN ('Salón de Fiestas', 'Parrilla', 'Piscina', 'Otro')),
    FECHA_RESERVA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    ID_USUARIO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_RESERVA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_HORA_RESERVA CHECK (HORA_FIN > HORA_INICIO)
);
GO

-- 📝 Tabla MAE_ACTA (Meeting Minutes)
CREATE TABLE dbo.MAE_ACTA
(
    ID_ACTA INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    FECHA_REUNION DATE NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    RUTA_ARCHIVO VARCHAR(255) NULL,
    ID_USUARIO_REGISTRO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_ACTA_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- ⚠️ Tabla MAE_INCIDENCIA (Incidents)
CREATE TABLE dbo.MAE_INCIDENCIA
(
    ID_INCIDENCIA INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    TIPO_INCIDENCIA VARCHAR(50) NOT NULL CHECK (TIPO_INCIDENCIA IN ('Ruido', 'Mantenimiento', 'Seguridad', 'Otro')),
    DESCRIPCION TEXT NOT NULL,
    FECHA_REPORTE DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_RESOLUCION DATETIME NULL,
    ID_USUARIO_REPORTE INT NOT NULL,
    ID_USUARIO_RESOLUCION INT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_INCIDENCIA_USUARIO_REPORTE FOREIGN KEY (ID_USUARIO_REPORTE) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT FK_INCIDENCIA_USUARIO_RESOLUCION FOREIGN KEY (ID_USUARIO_RESOLUCION) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_INCIDENCIA CHECK (FECHA_RESOLUCION IS NULL OR FECHA_RESOLUCION > FECHA_REPORTE)
);
GO

-- 📢 Tabla MAE_AVISO (Notices)
CREATE TABLE dbo.MAE_AVISO
(
    ID_AVISO INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    FECHA_PUBLICACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_EXPIRACION DATETIME NULL,
    ID_USUARIO_PUBLICACION INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_AVISO_USUARIO FOREIGN KEY (ID_USUARIO_PUBLICACION) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_AVISO CHECK (FECHA_EXPIRACION IS NULL OR FECHA_EXPIRACION > FECHA_PUBLICACION)
);
GO

-- 🚪 Tabla MAE_PUERTA (Doors)
CREATE TABLE dbo.MAE_PUERTA
(
    ID_PUERTA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(255) NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1))
);
GO

-- 🔑 Tabla MAE_QR (QR Codes for Doors)
CREATE TABLE dbo.MAE_QR
(
    ID_QR INT IDENTITY(1,1) PRIMARY KEY,
    QR_DATA VARCHAR(255) NOT NULL UNIQUE,
    ID_PUERTA INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_QR_PUERTA FOREIGN KEY (ID_PUERTA) REFERENCES MAE_PUERTA(ID_PUERTA) ON DELETE CASCADE
);
GO

-- 🔐 Tabla MAE_QR_TIPO_USUARIO (QR Code Permissions by User Type)
CREATE TABLE dbo.MAE_QR_TIPO_USUARIO
(
    ID_QR INT NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,

    -- Claves foráneas
    CONSTRAINT FK_QR_TIPO_QR FOREIGN KEY (ID_QR) REFERENCES MAE_QR(ID_QR) ON DELETE CASCADE,
    CONSTRAINT FK_QR_TIPO_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE,
    PRIMARY KEY (ID_QR, ID_TIPO_USUARIO)
);
GO

-- 📜 Tabla MAE_ACCESO_PUERTA (Door Access Logs)
CREATE TABLE dbo.MAE_ACCESO_PUERTA
(
    ID_ACCESO INT IDENTITY(1,1) PRIMARY KEY,
    ID_QR INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA_ACCESO DATETIME NOT NULL DEFAULT GETDATE(),
    EXITO BIT NOT NULL CHECK (EXITO IN (0, 1)),
    MOTIVO_FALLO VARCHAR(255) NULL,

    -- Claves foráneas
    CONSTRAINT FK_ACCESO_QR FOREIGN KEY (ID_QR) REFERENCES MAE_QR(ID_QR) ON DELETE NO ACTION,
    CONSTRAINT FK_ACCESO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- 🏢 Tabla MAE_FASE (Fases)
CREATE TABLE dbo.MAE_FASE
(
    ID_FASE INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL UNIQUE CHECK (NOMBRE IN ('Fase1', 'Fase2', 'Fase3')),
    DESCRIPCION VARCHAR(255) NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)) -- 0 = Inactivo, 1 = Activo
);
GO

-- 👤 Tabla MAE_USUARIO_FASE (Relación Usuarios-Fases)
CREATE TABLE dbo.MAE_USUARIO_FASE
(
    ID_USUARIO INT NOT NULL,
    ID_FASE INT NOT NULL,
    FECHA_ASIGNACION DATE NOT NULL DEFAULT GETDATE(),
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)), -- 0 = Inactivo, 1 = Activo

    -- Claves foráneas
    CONSTRAINT FK_USUARIO_FASE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_FASE_FASE FOREIGN KEY (ID_FASE) REFERENCES MAE_FASE(ID_FASE) ON DELETE CASCADE,
    PRIMARY KEY (ID_USUARIO, ID_FASE)
);
GO

-- 🚪 Tabla MAE_FASE_PUERTA (Relación Fases-Puertas)
CREATE TABLE dbo.MAE_FASE_PUERTA
(
    ID_FASE INT NOT NULL,
    ID_PUERTA INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)), -- 0 = Inactivo, 1 = Activo

    -- Claves foráneas
    CONSTRAINT FK_FASE_PUERTA_FASE FOREIGN KEY (ID_FASE) REFERENCES MAE_FASE(ID_FASE) ON DELETE CASCADE,
    CONSTRAINT FK_FASE_PUERTA_PUERTA FOREIGN KEY (ID_PUERTA) REFERENCES MAE_PUERTA(ID_PUERTA) ON DELETE CASCADE,
    PRIMARY KEY (ID_FASE, ID_PUERTA)
);
GO

-- 🛠️ Indexes for Performance
CREATE INDEX IDX_MAE_USUARIO_DNI ON MAE_USUARIO(DNI);
CREATE INDEX IDX_MAE_VISITA_FECHA_INGRESO ON MAE_VISITA(FECHA_INGRESO);
CREATE INDEX IDX_MAE_DEUDOR_ESTADO ON MAE_DEUDOR(ESTADO);
CREATE INDEX IDX_MAE_QR_QR_DATA ON MAE_QR(QR_DATA);
CREATE INDEX IDX_MAE_ACCESO_PUERTA_FECHA ON MAE_ACCESO_PUERTA(FECHA_ACCESO);
CREATE INDEX IDX_MAE_USUARIO_FASE_ID_USUARIO ON MAE_USUARIO_FASE(ID_USUARIO);
CREATE INDEX IDX_MAE_USUARIO_FASE_ID_FASE ON MAE_USUARIO_FASE(ID_FASE);
CREATE INDEX IDX_MAE_FASE_PUERTA_ID_FASE ON MAE_FASE_PUERTA(ID_FASE);
CREATE INDEX IDX_MAE_FASE_PUERTA_ID_PUERTA ON MAE_FASE_PUERTA(ID_PUERTA);
GO

-- 📊 View for Active Debtors Report
CREATE VIEW VW_DEUDORES_ACTIVOS
AS
SELECT 
    u.NOMBRES, 
    u.APELLIDOS, 
    d.NRO_DPTO, 
    d.MONTO, 
    d.FECHA_VENCIMIENTO, 
    DATEDIFF(DAY, d.FECHA_VENCIMIENTO, GETDATE()) AS DIAS_MOROSOS
FROM MAE_DEUDOR d
JOIN MAE_USUARIO u ON d.DNI = u.DNI
WHERE d.ESTADO = 0;
GO

-- 📊 View for Users, Phases, and Door Access Report
CREATE VIEW VW_USUARIOS_FASES_PUERTAS
AS
SELECT 
    u.ID_USUARIO,
    u.NOMBRES,
    u.APELLIDOS,
    f.NOMBRE AS FASE,
    p.NOMBRE AS PUERTA,
    fp.ESTADO AS ESTADO_ACCESO
FROM MAE_USUARIO u
JOIN MAE_USUARIO_FASE uf ON u.ID_USUARIO = uf.ID_USUARIO
JOIN MAE_FASE f ON uf.ID_FASE = f.ID_FASE
JOIN MAE_FASE_PUERTA fp ON f.ID_FASE = fp.ID_FASE
JOIN MAE_PUERTA p ON fp.ID_PUERTA = p.ID_PUERTA
WHERE uf.ESTADO = 1 AND f.ESTADO = 1 AND fp.ESTADO = 1 AND p.ESTADO = 1;
GO

/*08-04-2025*/
CREATE TABLE dbo.MAE_IMAGENES_LOGIN
(
    ID_IMAGEN INT IDENTITY(1,1) PRIMARY KEY,
    RUTA_IMAGEN VARBINARY(MAX) NOT NULL,  -- La imagen encriptada
    NOMBRE_IMAGEN VARCHAR(255) NOT NULL,
    TIPO_IMAGEN VARCHAR(50) NOT NULL,  -- Tipo de imagen (por ejemplo: 'jpg', 'png')
    FECHA_SUBIDA DATETIME NOT NULL DEFAULT GETDATE(),
    ID_USUARIO_SUBIDA INT NOT NULL,  -- El usuario que sube la imagen
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),  -- Estado de la imagen (activa/inactiva)
    
    -- Relación con la tabla de usuarios
    CONSTRAINT FK_IMAGEN_USUARIO FOREIGN KEY (ID_USUARIO_SUBIDA) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

CREATE TABLE MAE_USUARIO_DEPARTAMENTO (
    ID_USUARIO_DEPARTAMENTO INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT NOT NULL,
    NRO_DPTO INT NOT NULL,
    ESTADO BIT DEFAULT 1,
    FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO),
    CONSTRAINT UK_USUARIO_DPTO UNIQUE (ID_USUARIO, NRO_DPTO)
);
GO

/*18-04-2025*/
CREATE TABLE dbo.MAE_CUENTA_MANCOMUNADA
(
    ID_CUENTA INT IDENTITY(1,1) PRIMARY KEY,
    BANCO VARCHAR(100) NOT NULL,
    NUMERO_CUENTA VARCHAR(50) NOT NULL UNIQUE,
    CCI VARCHAR(50) NOT NULL UNIQUE,
    TITULAR VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)), -- 0 = Inactivo, 1 = Activo
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    ID_USUARIO_CREACION INT NOT NULL,
    CONSTRAINT FK_CUENTA_USUARIO FOREIGN KEY (ID_USUARIO_CREACION) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- Agregar la columna con un valor predeterminado
ALTER TABLE MAE_DEUDOR
ADD ID_USUARIO INT NOT NULL DEFAULT 1;
GO

ALTER TABLE MAE_DEUDOR
ADD CONSTRAINT FK_DEUDOR_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION;
GO

--TABLAS NUEVAS
CREATE TABLE MAE_ELEMENTOS_DASHBOARD (
    ID_ELEMENTO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_ELEMENTO VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(100) NULL,
    ORDEN INT NOT NULL DEFAULT 0 CHECK (ORDEN >= 0),
    ICONO VARCHAR(50) NULL, -- Ejemplo: 'FaExclamationCircle', 'FaBell'
    ESTADO BIT NOT NULL DEFAULT 1 CHECK (ESTADO IN (0, 1))
);
GO

CREATE NONCLUSTERED INDEX IDX_MAE_ELEMENTOS_DASHBOARD_ESTADO_ORDEN
ON MAE_ELEMENTOS_DASHBOARD(ESTADO, ORDEN)
INCLUDE (ID_ELEMENTO, NOMBRE_ELEMENTO, DESCRIPCION, ICONO);



CREATE TABLE MAE_PERMISOS_DASHBOARD (
    ID_PERMISO INT IDENTITY(1,1) PRIMARY KEY,
    ID_TIPO_USUARIO INT NOT NULL,
    ID_ELEMENTO INT NOT NULL,
    VISIBLE BIT NOT NULL DEFAULT 1,
    CONSTRAINT FK_PERMISO_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO),
    CONSTRAINT FK_PERMISO_ELEMENTO FOREIGN KEY (ID_ELEMENTO) REFERENCES MAE_ELEMENTOS_DASHBOARD(ID_ELEMENTO),
    CONSTRAINT UQ_TIPOUSUARIO_ELEMENTO UNIQUE (ID_TIPO_USUARIO, ID_ELEMENTO)
);
GO
--Crear un índice compuesto para MAE_PERMISOS_DASHBOARD y otro para MAE_ELEMENTOS_DASHBOARD
CREATE NONCLUSTERED INDEX IDX_MAE_PERMISOS_DASHBOARD_TIPO_VISIBLE
ON MAE_PERMISOS_DASHBOARD(ID_TIPO_USUARIO, VISIBLE)
INCLUDE (ID_ELEMENTO);

--Solución: Crear índices para mejorar la búsqueda por ID_USUARIO
CREATE NONCLUSTERED INDEX IDX_MAE_USUARIO_ID_ESTADO
ON MAE_USUARIO(ID_USUARIO, ESTADO)
INCLUDE (ID_TIPO_USUARIO);

CREATE NONCLUSTERED INDEX IDX_MAE_USUARIO_ROL_ID_USUARIO
ON MAE_USUARIO_ROL(ID_USUARIO)
INCLUDE (ID_TIPO_USUARIO);

CREATE NONCLUSTERED INDEX IDX_MAE_ELEMENTOS_DASHBOARD_ESTADO
ON MAE_ELEMENTOS_DASHBOARD(ESTADO)
INCLUDE (ID_ELEMENTO, NOMBRE_ELEMENTO);

--El índice único ya cubre ID_USUARIO, pero incluir ESTADO puede mejorar el rendimiento.

CREATE NONCLUSTERED INDEX IDX_MAE_USUARIO_DEPARTAMENTO_ID_ESTADO
ON MAE_USUARIO_DEPARTAMENTO(ID_USUARIO, ESTADO)
INCLUDE (NRO_DPTO);

--El índice en ESTADO no incluye NRO_DPTO ni MONTO, lo que obliga a escanear más filas.

CREATE NONCLUSTERED INDEX IDX_MAE_DEUDOR_NRO_DPTO_ESTADO
ON MAE_DEUDOR(NRO_DPTO, ESTADO)
INCLUDE (MONTO);

--La ordenación por FECHA_CREACION y el filtro ESTADO = 1 pueden ser lentos sin un índice.

CREATE NONCLUSTERED INDEX IDX_MAE_CUENTA_MANCOMUNADA_ESTADO_FECHA
ON MAE_CUENTA_MANCOMUNADA(ESTADO, FECHA_CREACION DESC)
INCLUDE (BANCO, NUMERO_CUENTA, CCI, TITULAR);

--Similar a noticias, el filtro y la ordenación necesitan un índice.

CREATE NONCLUSTERED INDEX IDX_MAE_MANTENIMIENTO_ESTADO_FECHA
ON MAE_MANTENIMIENTO(ESTADO, FECHA_MANTENIMIENTO)
INCLUDE (DESCRIPCION)
WHERE ESTADO = 1;

--Consulta de Documentos INDEX

CREATE NONCLUSTERED INDEX IDX_MAE_DOCUMENTO_ADMIN_ESTADO_FECHA
ON MAE_DOCUMENTO_ADMIN(ESTADO, FECHA_SUBIDA DESC)
INCLUDE (TITULO, TIPO_DOCUMENTO, RUTA_ARCHIVO);

--El JOIN y los filtros en ESTADO, FECHA_ENTREGA, y ID_USUARIO necesitan optimización.

CREATE NONCLUSTERED INDEX IDX_MAE_ENCARGO_ESTADO_FECHA
ON MAE_ENCARGO(ESTADO, FECHA_ENTREGA, NRO_DPTO)
INCLUDE (ID_ENCARGO, DESCRIPCION, FECHA_RECEPCION);


CREATE NONCLUSTERED INDEX IDX_MAE_AVISO_PERMISOS_ID_AVISO
ON MAE_AVISO_PERMISOS(ID_AVISO)
INCLUDE (ID_TIPO_USUARIO);


--TABLA DE EVENTOS
CREATE TABLE MAE_EVENTO (
    ID_EVENTO INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    TIPO_EVENTO VARCHAR(50) NOT NULL CHECK (TIPO_EVENTO IN ('Reunión', 'Mantenimiento', 'Actividad Social', 'Inspección', 'Otro')),
    FECHA_EVENTO DATE NOT NULL,
    HORA_INICIO TIME NULL,
    HORA_FIN TIME NULL,
    UBICACION VARCHAR(100) NULL,
    ID_USUARIO_REGISTRO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),
    CONSTRAINT FK_EVENTO_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_HORA_EVENTO CHECK (HORA_FIN IS NULL OR HORA_FIN > HORA_INICIO)
);
GO

CREATE NONCLUSTERED INDEX IDX_MAE_EVENTO_ESTADO_FECHA
ON MAE_EVENTO(ESTADO, FECHA_EVENTO)
INCLUDE (TITULO, DESCRIPCION, TIPO_EVENTO, HORA_INICIO, HORA_FIN, UBICACION)
WHERE ESTADO = 1;


-- Tabla para permisos de noticias por tipo de usuario
CREATE TABLE MAE_AVISO_PERMISOS (
    ID_AVISO INT NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,
    CONSTRAINT PK_AVISO_PERMISOS PRIMARY KEY (ID_AVISO, ID_TIPO_USUARIO),
    CONSTRAINT FK_AVISO_PERMISOS_AVISO FOREIGN KEY (ID_AVISO) REFERENCES MAE_AVISO(ID_AVISO) ON DELETE CASCADE,
    CONSTRAINT FK_AVISO_PERMISOS_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE
);
GO

-- Tabla para permisos de eventos por tipo de usuario
CREATE TABLE MAE_EVENTO_PERMISOS (
    ID_EVENTO INT NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,
    CONSTRAINT PK_EVENTO_PERMISOS PRIMARY KEY (ID_EVENTO, ID_TIPO_USUARIO),
    CONSTRAINT FK_EVENTO_PERMISOS_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES MAE_EVENTO(ID_EVENTO) ON DELETE CASCADE,
    CONSTRAINT FK_EVENTO_PERMISOS_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE
);
GO

-- Tabla para permisos de documentos por tipo de usuario
CREATE TABLE MAE_DOCUMENTO_PERMISOS (
    ID_DOCUMENTO INT NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,
    CONSTRAINT PK_DOCUMENTO_PERMISOS PRIMARY KEY (ID_DOCUMENTO, ID_TIPO_USUARIO),
    CONSTRAINT FK_DOCUMENTO_PERMISOS_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES MAE_DOCUMENTO_ADMIN(ID_DOCUMENTO) ON DELETE CASCADE,
    CONSTRAINT FK_DOCUMENTO_PERMISOS_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE
);
GO

-- Tabla para registrar cambios
CREATE TABLE MAE_CAMBIO_LOG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL CHECK (TIPO IN ('news', 'events', 'documents')),
    FECHA_CAMBIO DATETIME NOT NULL DEFAULT GETDATE(),
    PROCESADO BIT NOT NULL DEFAULT 0
);
GO

-- Trigger para MAE_AVISO
CREATE TRIGGER TRG_MAE_AVISO_CHANGE
ON MAE_AVISO
AFTER INSERT, UPDATE
AS
BEGIN
    INSERT INTO MAE_CAMBIO_LOG (TIPO)
    VALUES ('news');
END;
GO

-- Trigger para MAE_EVENTO
CREATE TRIGGER TRG_MAE_EVENTO_CHANGE
ON MAE_EVENTO
AFTER INSERT, UPDATE
AS
BEGIN
    INSERT INTO MAE_CAMBIO_LOG (TIPO)
    VALUES ('events');
END;
GO

-- Trigger para MAE_DOCUMENTO_ADMIN
CREATE TRIGGER TRG_MAE_DOCUMENTO_CHANGE
ON MAE_DOCUMENTO_ADMIN
AFTER INSERT, UPDATE
AS
BEGIN
    INSERT INTO MAE_CAMBIO_LOG (TIPO)
    VALUES ('documents');
END;
GO