-- 🏷 Tabla MAE_TIPO_USUARIO (User Types)
CREATE TABLE dbo.MAE_TIPO_USUARIO
(
    ID_TIPO_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    DETALLE_USUARIO VARCHAR(20) NOT NULL UNIQUE,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)) -- 0 = Inactivo, 1 = Activo
);
GO

-- 🏷 Tabla MAE_SEXO (Gender)
CREATE TABLE dbo.MAE_SEXO
(
    ID_SEXO INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPCION VARCHAR(10) NOT NULL UNIQUE CHECK (DESCRIPCION IN ('Masculino', 'Femenino'))
);
GO

-- 👤 Tabla MAE_USUARIO (Users/Residents)
CREATE TABLE dbo.MAE_USUARIO
(
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT,
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DNI VARCHAR(8) NOT NULL UNIQUE,
    CORREO VARCHAR(100) NULL,
    CELULAR VARCHAR(9) UNIQUE CHECK (CELULAR LIKE '[9]________'),
    CONTACTO_EMERGENCIA VARCHAR(9) CHECK (CONTACTO_EMERGENCIA LIKE '[9]________'),
    FECHA_NACIMIENTO DATE,
    ID_TIPO_USUARIO INT NOT NULL,
    ID_SEXO INT NOT NULL,
    DETALLE VARCHAR(100),
    OBSERVACIONES VARCHAR(200),
    COMITE BIT NOT NULL CHECK (COMITE IN (0, 1)), -- 0 = No, 1 = Sí
    USUARIO VARCHAR(50) UNIQUE NOT NULL,
    CONTRASENA_HASH VARCHAR(255) NOT NULL,  
    CONTRASENA_SALT VARCHAR(50) NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_USUARIO_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO),
    CONSTRAINT FK_USUARIO_SEXO FOREIGN KEY (ID_SEXO) REFERENCES MAE_SEXO(ID_SEXO)
);
GO

ALTER TABLE MAE_USUARIO
ADD PRIMER_INICIO BIT NOT NULL DEFAULT 1;

-- 🐶 Tabla MAE_MASCOTA (Pets)
CREATE TABLE dbo.MAE_MASCOTA
(
    ID_MASCOTA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK (TIPO IN ('Perro', 'Gato', 'Ave', 'Otro')),
    RAZA VARCHAR(50),
    EDAD INT CHECK (EDAD >= 0),
    DNI_DUENO VARCHAR(8) NOT NULL,

    -- Clave foránea
    CONSTRAINT FK_MASCOTA_USUARIO FOREIGN KEY (DNI_DUENO) REFERENCES MAE_USUARIO(DNI) ON DELETE CASCADE
);
GO

-- 📂 Tabla MAE_MENU (Main Menus)
CREATE TABLE dbo.MAE_MENU
(
    ID_MENU INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    ICONO VARCHAR(50) NULL,
    URL VARCHAR(100) NULL,
    ORDEN INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1))
);
GO

-- 📂 Tabla MAE_SUBMENU (Submenus)
CREATE TABLE dbo.MAE_SUBMENU
(
    ID_SUBMENU INT IDENTITY(1,1) PRIMARY KEY,
    ID_MENU INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    ICONO VARCHAR(50) NULL,
    URL VARCHAR(100) NOT NULL,
    ORDEN INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_SUBMENU_MENU FOREIGN KEY (ID_MENU) REFERENCES MAE_MENU(ID_MENU) ON DELETE CASCADE
);
GO

-- 🔐 Tabla MAE_ROL_MENU (Menu Permissions by User Type)
CREATE TABLE dbo.MAE_ROL_MENU
(
    ID_TIPO_USUARIO INT NOT NULL,
    ID_MENU INT NOT NULL,

    CONSTRAINT FK_ROL_MENU_TIPO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_ROL_MENU_MENU FOREIGN KEY (ID_MENU) REFERENCES MAE_MENU(ID_MENU) ON DELETE CASCADE
);
GO

-- 🔐 Tabla MAE_ROL_SUBMENU (Submenu Permissions by User Type)
CREATE TABLE dbo.MAE_ROL_SUBMENU
(
    ID_TIPO_USUARIO INT NOT NULL,
    ID_SUBMENU INT NOT NULL,

    CONSTRAINT FK_ROL_SUBMENU_TIPO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_ROL_SUBMENU_SUBMENU FOREIGN KEY (ID_SUBMENU) REFERENCES MAE_SUBMENU(ID_SUBMENU) ON DELETE CASCADE
);
GO

-- 🏢 Tabla MAE_PROPIETARIO (Property Owners)
CREATE TABLE dbo.MAE_PROPIETARIO
(
    ID_PROPIETARIO INT IDENTITY(1,1) PRIMARY KEY,
    DNI VARCHAR(8) NOT NULL,
    NRO_DPTO INT NOT NULL,
    FECHA_INICIO_PROPIEDAD DATE NOT NULL,
    FECHA_FIN_PROPIEDAD DATE NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_PROPIETARIO_USUARIO FOREIGN KEY (DNI) REFERENCES MAE_USUARIO(DNI) ON DELETE CASCADE,
    CONSTRAINT CHK_FECHA_PROPIEDAD CHECK (FECHA_FIN_PROPIEDAD IS NULL OR FECHA_FIN_PROPIEDAD > FECHA_INICIO_PROPIEDAD)
);
GO

-- 📜 Tabla MAE_DOCUMENTO_ADMIN (Administrative Documents)
CREATE TABLE dbo.MAE_DOCUMENTO_ADMIN
(
    ID_DOCUMENTO INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL,
    TIPO_DOCUMENTO VARCHAR(50) NOT NULL CHECK (TIPO_DOCUMENTO IN ('Reglamento', 'Contrato', 'Informe', 'Otro')),
    RUTA_ARCHIVO VARCHAR(255) NOT NULL,
    FECHA_SUBIDA DATE NOT NULL DEFAULT GETDATE(),
    ID_USUARIO_SUBIDA INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_DOCUMENTO_USUARIO FOREIGN KEY (ID_USUARIO_SUBIDA) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- 🚪 Tabla MAE_VISITA (Visits)
CREATE TABLE dbo.MAE_VISITA
(
    ID_VISITA INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    NOMBRE_VISITANTE VARCHAR(100) NOT NULL,
    DNI_VISITANTE VARCHAR(8) NOT NULL,
    FECHA_INGRESO DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_SALIDA DATETIME NULL,
    MOTIVO VARCHAR(100) NULL,
    ID_USUARIO_REGISTRO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_VISITA_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_VISITA CHECK (FECHA_SALIDA IS NULL OR FECHA_SALIDA > FECHA_INGRESO)
);
GO

-- 🔧 Tabla MAE_PROVEEDOR (Suppliers)
CREATE TABLE dbo.MAE_PROVEEDOR
(
    ID_PROVEEDOR INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    RUC VARCHAR(11) NOT NULL UNIQUE CHECK (RUC LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    TELEFONO VARCHAR(9) NULL CHECK (TELEFONO LIKE '[9]________'),
    CORREO VARCHAR(100) NULL,
    TIPO_SERVICIO VARCHAR(50) NOT NULL CHECK (TIPO_SERVICIO IN ('Mantenimiento', 'Limpieza', 'Seguridad', 'Otro')),
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1))
);
GO

-- 🔧 Tabla MAE_MANTENIMIENTO (Maintenance by Suppliers)
CREATE TABLE dbo.MAE_MANTENIMIENTO
(
    ID_MANTENIMIENTO INT IDENTITY(1,1) PRIMARY KEY,
    ID_PROVEEDOR INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA_MANTENIMIENTO DATE NOT NULL,
    COSTO DECIMAL(10, 2) NOT NULL CHECK (COSTO >= 0),
    NRO_DPTO INT NULL,
    ID_USUARIO_REGISTRO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_MANTENIMIENTO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES MAE_PROVEEDOR(ID_PROVEEDOR) ON DELETE NO ACTION,
    CONSTRAINT FK_MANTENIMIENTO_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- 📦 Tabla MAE_ENCARGO (Packages/Deliveries)
CREATE TABLE dbo.MAE_ENCARGO
(
    ID_ENCARGO INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA_RECEPCION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ENTREGA DATETIME NULL,
    ID_USUARIO_RECEPCION INT NOT NULL,
    ID_USUARIO_ENTREGA INT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_ENCARGO_USUARIO_RECEPCION FOREIGN KEY (ID_USUARIO_RECEPCION) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT FK_ENCARGO_USUARIO_ENTREGA FOREIGN KEY (ID_USUARIO_ENTREGA) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_ENCARGO CHECK (FECHA_ENTREGA IS NULL OR FECHA_ENTREGA > FECHA_RECEPCION)
);
GO

-- 💸 Tabla MAE_DEUDOR (Debtors/Delinquents)
CREATE TABLE dbo.MAE_DEUDOR
(
    ID_DEUDA INT IDENTITY(1,1) PRIMARY KEY,
    DNI VARCHAR(8) NOT NULL,
    NRO_DPTO INT NOT NULL,
    MONTO DECIMAL(10, 2) NOT NULL CHECK (MONTO > 0),
    FECHA_VENCIMIENTO DATE NOT NULL,
    FECHA_PAGO DATE NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_DEUDOR_USUARIO FOREIGN KEY (DNI) REFERENCES MAE_USUARIO(DNI) ON DELETE CASCADE,
    CONSTRAINT CHK_FECHA_PAGO CHECK (FECHA_PAGO IS NULL OR FECHA_PAGO >= FECHA_VENCIMIENTO)
);
GO

-- 📅 Tabla MAE_RESERVA (Reservations)
CREATE TABLE dbo.MAE_RESERVA
(
    ID_RESERVA INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    TIPO_AREA VARCHAR(50) NOT NULL CHECK (TIPO_AREA IN ('Salón de Fiestas', 'Parrilla', 'Piscina', 'Otro')),
    FECHA_RESERVA DATE NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    ID_USUARIO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_RESERVA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_HORA_RESERVA CHECK (HORA_FIN > HORA_INICIO)
);
GO

-- 📝 Tabla MAE_ACTA (Meeting Minutes)
CREATE TABLE dbo.MAE_ACTA
(
    ID_ACTA INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    FECHA_REUNION DATE NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    RUTA_ARCHIVO VARCHAR(255) NULL,
    ID_USUARIO_REGISTRO INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_ACTA_USUARIO FOREIGN KEY (ID_USUARIO_REGISTRO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- ⚠️ Tabla MAE_INCIDENCIA (Incidents)
CREATE TABLE dbo.MAE_INCIDENCIA
(
    ID_INCIDENCIA INT IDENTITY(1,1) PRIMARY KEY,
    NRO_DPTO INT NOT NULL,
    TIPO_INCIDENCIA VARCHAR(50) NOT NULL CHECK (TIPO_INCIDENCIA IN ('Ruido', 'Mantenimiento', 'Seguridad', 'Otro')),
    DESCRIPCION TEXT NOT NULL,
    FECHA_REPORTE DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_RESOLUCION DATETIME NULL,
    ID_USUARIO_REPORTE INT NOT NULL,
    ID_USUARIO_RESOLUCION INT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Claves foráneas
    CONSTRAINT FK_INCIDENCIA_USUARIO_REPORTE FOREIGN KEY (ID_USUARIO_REPORTE) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT FK_INCIDENCIA_USUARIO_RESOLUCION FOREIGN KEY (ID_USUARIO_RESOLUCION) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_INCIDENCIA CHECK (FECHA_RESOLUCION IS NULL OR FECHA_RESOLUCION > FECHA_REPORTE)
);
GO

-- 📢 Tabla MAE_AVISO (Notices)
CREATE TABLE dbo.MAE_AVISO
(
    ID_AVISO INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    FECHA_PUBLICACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_EXPIRACION DATETIME NULL,
    ID_USUARIO_PUBLICACION INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_AVISO_USUARIO FOREIGN KEY (ID_USUARIO_PUBLICACION) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION,
    CONSTRAINT CHK_FECHA_AVISO CHECK (FECHA_EXPIRACION IS NULL OR FECHA_EXPIRACION > FECHA_PUBLICACION)
);
GO

-- 🚪 Tabla MAE_PUERTA (Doors)
CREATE TABLE dbo.MAE_PUERTA
(
    ID_PUERTA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(255) NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1))
);
GO

-- 🔑 Tabla MAE_QR (QR Codes for Doors)
CREATE TABLE dbo.MAE_QR
(
    ID_QR INT IDENTITY(1,1) PRIMARY KEY,
    QR_DATA VARCHAR(255) NOT NULL UNIQUE,
    ID_PUERTA INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)),

    -- Clave foránea
    CONSTRAINT FK_QR_PUERTA FOREIGN KEY (ID_PUERTA) REFERENCES MAE_PUERTA(ID_PUERTA) ON DELETE CASCADE
);
GO

-- 🔐 Tabla MAE_QR_TIPO_USUARIO (QR Code Permissions by User Type)
CREATE TABLE dbo.MAE_QR_TIPO_USUARIO
(
    ID_QR INT NOT NULL,
    ID_TIPO_USUARIO INT NOT NULL,

    -- Claves foráneas
    CONSTRAINT FK_QR_TIPO_QR FOREIGN KEY (ID_QR) REFERENCES MAE_QR(ID_QR) ON DELETE CASCADE,
    CONSTRAINT FK_QR_TIPO_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES MAE_TIPO_USUARIO(ID_TIPO_USUARIO) ON DELETE CASCADE,
    PRIMARY KEY (ID_QR, ID_TIPO_USUARIO)
);
GO

-- 📜 Tabla MAE_ACCESO_PUERTA (Door Access Logs)
CREATE TABLE dbo.MAE_ACCESO_PUERTA
(
    ID_ACCESO INT IDENTITY(1,1) PRIMARY KEY,
    ID_QR INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FECHA_ACCESO DATETIME NOT NULL DEFAULT GETDATE(),
    EXITO BIT NOT NULL CHECK (EXITO IN (0, 1)),
    MOTIVO_FALLO VARCHAR(255) NULL,

    -- Claves foráneas
    CONSTRAINT FK_ACCESO_QR FOREIGN KEY (ID_QR) REFERENCES MAE_QR(ID_QR) ON DELETE NO ACTION,
    CONSTRAINT FK_ACCESO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE NO ACTION
);
GO

-- 🏢 Tabla MAE_FASE (Fases)
CREATE TABLE dbo.MAE_FASE
(
    ID_FASE INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL UNIQUE CHECK (NOMBRE IN ('Fase1', 'Fase2', 'Fase3')),
    DESCRIPCION VARCHAR(255) NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)) -- 0 = Inactivo, 1 = Activo
);
GO

-- 👤 Tabla MAE_USUARIO_FASE (Relación Usuarios-Fases)
CREATE TABLE dbo.MAE_USUARIO_FASE
(
    ID_USUARIO INT NOT NULL,
    ID_FASE INT NOT NULL,
    FECHA_ASIGNACION DATE NOT NULL DEFAULT GETDATE(),
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)), -- 0 = Inactivo, 1 = Activo

    -- Claves foráneas
    CONSTRAINT FK_USUARIO_FASE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES MAE_USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_FASE_FASE FOREIGN KEY (ID_FASE) REFERENCES MAE_FASE(ID_FASE) ON DELETE CASCADE,
    PRIMARY KEY (ID_USUARIO, ID_FASE)
);
GO

-- 🚪 Tabla MAE_FASE_PUERTA (Relación Fases-Puertas)
CREATE TABLE dbo.MAE_FASE_PUERTA
(
    ID_FASE INT NOT NULL,
    ID_PUERTA INT NOT NULL,
    ESTADO BIT NOT NULL CHECK (ESTADO IN (0, 1)), -- 0 = Inactivo, 1 = Activo

    -- Claves foráneas
    CONSTRAINT FK_FASE_PUERTA_FASE FOREIGN KEY (ID_FASE) REFERENCES MAE_FASE(ID_FASE) ON DELETE CASCADE,
    CONSTRAINT FK_FASE_PUERTA_PUERTA FOREIGN KEY (ID_PUERTA) REFERENCES MAE_PUERTA(ID_PUERTA) ON DELETE CASCADE,
    PRIMARY KEY (ID_FASE, ID_PUERTA)
);
GO

-- 🛠️ Indexes for Performance
CREATE INDEX IDX_MAE_USUARIO_DNI ON MAE_USUARIO(DNI);
CREATE INDEX IDX_MAE_VISITA_FECHA_INGRESO ON MAE_VISITA(FECHA_INGRESO);
CREATE INDEX IDX_MAE_DEUDOR_ESTADO ON MAE_DEUDOR(ESTADO);
CREATE INDEX IDX_MAE_QR_QR_DATA ON MAE_QR(QR_DATA);
CREATE INDEX IDX_MAE_ACCESO_PUERTA_FECHA ON MAE_ACCESO_PUERTA(FECHA_ACCESO);
CREATE INDEX IDX_MAE_USUARIO_FASE_ID_USUARIO ON MAE_USUARIO_FASE(ID_USUARIO);
CREATE INDEX IDX_MAE_USUARIO_FASE_ID_FASE ON MAE_USUARIO_FASE(ID_FASE);
CREATE INDEX IDX_MAE_FASE_PUERTA_ID_FASE ON MAE_FASE_PUERTA(ID_FASE);
CREATE INDEX IDX_MAE_FASE_PUERTA_ID_PUERTA ON MAE_FASE_PUERTA(ID_PUERTA);
GO

-- 📊 View for Active Debtors Report
CREATE VIEW VW_DEUDORES_ACTIVOS
AS
SELECT 
    u.NOMBRES, 
    u.APELLIDOS, 
    d.NRO_DPTO, 
    d.MONTO, 
    d.FECHA_VENCIMIENTO, 
    DATEDIFF(DAY, d.FECHA_VENCIMIENTO, GETDATE()) AS DIAS_MOROSOS
FROM MAE_DEUDOR d
JOIN MAE_USUARIO u ON d.DNI = u.DNI
WHERE d.ESTADO = 0;
GO

-- 📊 View for Users, Phases, and Door Access Report
CREATE VIEW VW_USUARIOS_FASES_PUERTAS
AS
SELECT 
    u.ID_USUARIO,
    u.NOMBRES,
    u.APELLIDOS,
    f.NOMBRE AS FASE,
    p.NOMBRE AS PUERTA,
    fp.ESTADO AS ESTADO_ACCESO
FROM MAE_USUARIO u
JOIN MAE_USUARIO_FASE uf ON u.ID_USUARIO = uf.ID_USUARIO
JOIN MAE_FASE f ON uf.ID_FASE = f.ID_FASE
JOIN MAE_FASE_PUERTA fp ON f.ID_FASE = fp.ID_FASE
JOIN MAE_PUERTA p ON fp.ID_PUERTA = p.ID_PUERTA
WHERE uf.ESTADO = 1 AND f.ESTADO = 1 AND fp.ESTADO = 1 AND p.ESTADO = 1;
GO

