-- INSERTAR FASES
INSERT INTO MAE_FASE (NOMBRE, DESCRIPCION, ESTADO) VALUES ('Fase1', 'Primera fase de la torre', 1);
INSERT INTO MAE_FASE (NOMBRE, DESCRIPCION, ESTADO) VALUES ('Fase2', 'Segunda fase de la torre', 1);
INSERT INTO MAE_FASE (NOMBRE, DESCRIPCION, ESTADO) VALUES ('Fase3', 'Tercera fase de la torre', 1);

-- INSERTAR PUERTAS
INSERT INTO MAE_PUERTA (NOMBRE, DESCRIPCION, ESTADO) VALUES ('Puerta A', 'Entrada principal Fase1', 1);
INSERT INTO MAE_PUERTA (NOMBRE, DESCRIPCION, ESTADO) VALUES ('Puerta B', 'Entrada principal Fase2', 1);
INSERT INTO MAE_PUERTA (NOMBRE, DESCRIPCION, ESTADO) VALUES ('Puerta C', 'Entrada principal Fase3', 1);

-- INSERTAR PUERTAS A FASES
INSERT INTO MAE_FASE_PUERTA (ID_FASE, ID_PUERTA, ESTADO) VALUES (1, 1, 1); -- Fase1 tiene acceso a Puerta A
INSERT INTO MAE_FASE_PUERTA (ID_FASE, ID_PUERTA, ESTADO) VALUES (2, 2, 1); -- Fase2 tiene acceso a Puerta B
INSERT INTO MAE_FASE_PUERTA (ID_FASE, ID_PUERTA, ESTADO) VALUES (3, 3, 1); -- Fase3 tiene acceso a Puerta C

-- INSERTAR QR CODE
INSERT INTO MAE_QR (QR_DATA, ID_PUERTA, ESTADO)
VALUES ('qr_code_123', 1, 1);

-- INSERTAR TIPOS DE USUARIOS
INSERT INTO MAE_TIPO_USUARIO (DETALLE_USUARIO, ESTADO)
VALUES ('Sistemas', 1), ('Administrador', 1), ('Seguridad', 1), ('Propietario', 1), ('Inquilino', 1);

-- INSERTAR GENERO
INSERT INTO MAE_SEXO (DESCRIPCION)
VALUES ('Masculino'), ('Femenino');


-- INSERTAR ELEMENTOS DASHBOARD
INSERT INTO MAE_ELEMENTOS_DASHBOARD (NOMBRE_ELEMENTO, DESCRIPCION, ESTADO) VALUES
('DEUDORES', 'Sección de deudas pendientes (botón y card)', 1),
('CUENTA_MANCOMUNADA', 'Sección de cuenta mancomunada (botón y card)', 1),
('NOTICIAS', 'Sección de noticias (botón y card)', 1),
('EVENTOS', 'Sección de eventos (botón y card)', 1),
('DOCUMENTOS', 'Sección de documentos (botón y card)', 1),
('ENCARGOS', 'Sección de encargos pendientes (botón y card)', 1),
('BOTON_REPORTAR_PROBLEMA', 'Botón para reportar un problema (modal)', 1);
GO

--PERMISOS DE ELEMENTOS DASHBOARD
-- Sistemas: Ve todo
INSERT INTO MAE_PERMISOS_DASHBOARD (ID_TIPO_USUARIO, ID_ELEMENTO, VISIBLE)
SELECT 1, ID_ELEMENTO, 1 FROM MAE_ELEMENTOS_DASHBOARD;

-- Administrador: Ve todo excepto DEUDORES
INSERT INTO MAE_PERMISOS_DASHBOARD (ID_TIPO_USUARIO, ID_ELEMENTO, VISIBLE)
SELECT 2, ID_ELEMENTO, CASE WHEN NOMBRE_ELEMENTO = 'DEUDORES' THEN 0 ELSE 1 END
FROM MAE_ELEMENTOS_DASHBOARD;

-- Comité: Ve todo excepto DEUDORES y ENCARGOS
INSERT INTO MAE_PERMISOS_DASHBOARD (ID_TIPO_USUARIO, ID_ELEMENTO, VISIBLE)
SELECT 3, ID_ELEMENTO, CASE WHEN NOMBRE_ELEMENTO IN ('DEUDORES', 'ENCARGOS') THEN 0 ELSE 1 END
FROM MAE_ELEMENTOS_DASHBOARD;

-- Seguridad: Solo ve NOTICIAS, EVENTOS, y BOTON_REPORTAR_PROBLEMA
INSERT INTO MAE_PERMISOS_DASHBOARD (ID_TIPO_USUARIO, ID_ELEMENTO, VISIBLE)
SELECT 4, ID_ELEMENTO, CASE WHEN NOMBRE_ELEMENTO IN ('NOTICIAS', 'EVENTOS', 'BOTON_REPORTAR_PROBLEMA') THEN 1 ELSE 0 END
FROM MAE_ELEMENTOS_DASHBOARD;

-- Propietario: Ve todo
INSERT INTO MAE_PERMISOS_DASHBOARD (ID_TIPO_USUARIO, ID_ELEMENTO, VISIBLE)
SELECT 5, ID_ELEMENTO, 1 FROM MAE_ELEMENTOS_DASHBOARD;

-- Inquilino: Ve todo
INSERT INTO MAE_PERMISOS_DASHBOARD (ID_TIPO_USUARIO, ID_ELEMENTO, VISIBLE)
SELECT 6, ID_ELEMENTO, 1 FROM MAE_ELEMENTOS_DASHBOARD;
GO



--#########################################################################
--Insertar USUARIO DE PRUEBA
INSERT INTO MAE_USUARIO (
    NRO_DPTO, NOMBRES, APELLIDOS, DNI, CORREO, CELULAR, CONTACTO_EMERGENCIA, 
    FECHA_NACIMIENTO, ID_TIPO_USUARIO, ID_SEXO, DETALLE, OBSERVACIONES, COMITE, 
    USUARIO, CONTRASENA_HASH, CONTRASENA_SALT, ESTADO
)
VALUES (
    101, -- NRO_DPTO
    'Juan', -- NOMBRES
    'Pérez', -- APELLIDOS
    '12345678', -- DNI
    'test@example.com', -- CORREO
    '987654321', -- CELULAR
    '912345678', -- CONTACTO_EMERGENCIA
    '1990-01-01', -- FECHA_NACIMIENTO
    1, -- ID_TIPO_USUARIO (de MAE_TIPO_USUARIO)
    1, -- ID_SEXO (de MAE_SEXO)
    'Residente principal', -- DETALLE
    'Ninguna', -- OBSERVACIONES
    0, -- COMITE (0 = No)
    'juanperez', -- USUARIO
    '$2b$10$tKtKXhg63LWfN1hiWNkxKubVXTep3Ct/FqcxzETmphnJldzu16UGm', -- CONTRASENA_HASH
    '$2b$10$J22rsc5zqm3COkERoc4DuO', -- CONTRASENA_SALT
    1 -- ESTADO (1 = Activo)
);

-- Asignar USUARIO PRUEBA FASE
INSERT INTO MAE_USUARIO_FASE (ID_USUARIO, ID_FASE, ESTADO) VALUES (1, 1, 1); 
--#########################################################################





