--ASIGNAR TOS LOS MENUS AL TIPO DE USUARIO
--SISTEMAS
EXEC SP_INSERTAR_ROL_MENU @ID_TIPO_USUARIO = 1, @ID_MENU = 1;
EXEC SP_INSERTAR_ROL_MENU @ID_TIPO_USUARIO = 1, @ID_MENU = 2;
EXEC SP_INSERTAR_ROL_MENU @ID_TIPO_USUARIO = 1, @ID_MENU = 3;


--ASIGNAR TOS LOS SUB-MENUS AL TIPO DE USUARIO
--SISTEMAS
-- Submenus del menu 1 (Usuarios)
EXEC SP_INSERTAR_ROL_SUBMENU @ID_TIPO_USUARIO = 1, @ID_SUBMENU = 1;
EXEC SP_INSERTAR_ROL_SUBMENU @ID_TIPO_USUARIO = 1, @ID_SUBMENU = 2;

-- Submenus del menu 2 (Control de Accesos)
EXEC SP_INSERTAR_ROL_SUBMENU @ID_TIPO_USUARIO = 1, @ID_SUBMENU = 3;
EXEC SP_INSERTAR_ROL_SUBMENU @ID_TIPO_USUARIO = 1, @ID_SUBMENU = 4;

-- Submenu del menu 3 (Configuracion)
EXEC SP_INSERTAR_ROL_SUBMENU @ID_TIPO_USUARIO = 1, @ID_SUBMENU =5;
