ALTER PROCEDURE SP_INSERTAR_MENU
    @NOMBRE VARCHAR(50),
    @ICONO VARCHAR(50),
    @URL VARCHAR(100),
    @ORDEN INT,
    @ESTADO BIT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM MAE_MENU WHERE NOMBRE = @NOMBRE
    )
    BEGIN
        INSERT INTO MAE_MENU (NOMBRE, ICONO, URL, ORDEN, ESTADO)
        VALUES (@NOMBRE, @ICONO, @URL, @ORDEN, @ESTADO);
    END
END;
GO

-- Insertar un menú
--EXEC SP_INSERTAR_MENU 'Gestión', 'settings', '/gestion', 1, 1;
