ALTER PROCEDURE SP_INSERTAR_SUBMENU
    @ID_MENU INT,
    @NOMBRE VARCHAR(50),
    @ICONO VARCHAR(50),
    @URL VARCHAR(100),
    @ORDEN INT,
    @ESTADO BIT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM MAE_SUBMENU WHERE NOMBRE = @NOMBRE
    )
    BEGIN
        INSERT INTO MAE_SUBMENU (ID_MENU, NOMBRE, ICONO, URL, ORDEN, ESTADO)
        VALUES (@ID_MENU, @NOMBRE, @ICONO, @URL, @ORDEN, @ESTADO);
    END
END;
GO

-- Insertar un submenú
--EXEC SP_INSERTAR_SUBMENU 1, 'Usuarios', 'user', '/gestion/usuarios', 1, 1;