ALTER PROCEDURE SP_INSERTAR_ROL_MENU
    @ID_TIPO_USUARIO INT,
    @ID_MENU INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM MAE_ROL_MENU
        WHERE ID_TIPO_USUARIO = @ID_TIPO_USUARIO AND ID_MENU = @ID_MENU
    )
    BEGIN
        INSERT INTO MAE_ROL_MENU (ID_TIPO_USUARIO, ID_MENU)
        VALUES (@ID_TIPO_USUARIO, @ID_MENU);
    END
END;
GO

