ALTER PROCEDURE SP_INSERTAR_ROL_SUBMENU
    @ID_TIPO_USUARIO INT,
    @ID_SUBMENU INT
AS
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM MAE_ROL_SUBMENU
        WHERE ID_TIPO_USUARIO = @ID_TIPO_USUARIO AND ID_SUBMENU = @ID_SUBMENU
    )
    BEGIN
        INSERT INTO MAE_ROL_SUBMENU (ID_TIPO_USUARIO, ID_SUBMENU)
        VALUES (@ID_TIPO_USUARIO, @ID_SUBMENU);
    END
END;
GO
