CREATE PROCEDURE SP_ELIMINAR_ROL_MENU
    @ID_TIPO_USUARIO INT,
    @ID_MENU INT
AS
BEGIN
    DELETE FROM MAE_ROL_MENU
    WHERE ID_TIPO_USUARIO = @ID_TIPO_USUARIO AND ID_MENU = @ID_MENU;
END;
GO

-- Eliminar acceso de tipo 3 al menú 5
--EXEC SP_ELIMINAR_ROL_MENU 3, 5;