ALTER PROCEDURE SP_ELIMINAR_ROL_SUBMENU
    @ID_TIPO_USUARIO INT,
    @ID_SUBMENU INT
AS
BEGIN
    DELETE FROM MAE_ROL_SUBMENU
    WHERE ID_TIPO_USUARIO = @ID_TIPO_USUARIO AND ID_SUBMENU = @ID_SUBMENU;
END;
GO

-- Eliminar acceso de tipo 2 al submenú 10
--EXEC SP_ELIMINAR_ROL_SUBMENU 2, 10;
