ALTER PROCEDURE SP_GET_MENUS_CON_SUBMENUS_POR_USUARIO
    @ID_USUARIO INT
AS
BEGIN
    -- Obtenemos todos los roles (principal + adicionales)
    SELECT DISTINCT 
        m.ID_MENU, m.NOMBRE AS MENU_NOMBRE, m.ICONO AS MENU_ICONO, m.URL AS MENU_URL, m.ORDEN AS MENU_ORDEN,
        sm.ID_SUBMENU, sm.NOMBRE AS SUBMENU_NOMBRE, sm.ICONO AS SUBMENU_ICONO, sm.URL AS SUBMENU_URL, sm.ORDEN AS SUBMENU_ORDEN
    FROM MAE_MENU m
    JOIN MAE_ROL_MENU rm ON rm.ID_MENU = m.ID_MENU
    JOIN (
        SELECT ID_TIPO_USUARIO FROM MAE_USUARIO WHERE ID_USUARIO = @ID_USUARIO
        UNION
        SELECT ID_TIPO_USUARIO FROM MAE_USUARIO_ROL WHERE ID_USUARIO = @ID_USUARIO
    ) AS roles ON roles.ID_TIPO_USUARIO = rm.ID_TIPO_USUARIO
    LEFT JOIN MAE_SUBMENU sm ON sm.ID_MENU = m.ID_MENU AND sm.ESTADO = 1
    LEFT JOIN MAE_ROL_SUBMENU rs ON rs.ID_SUBMENU = sm.ID_SUBMENU AND rs.ID_TIPO_USUARIO = roles.ID_TIPO_USUARIO
    WHERE m.ESTADO = 1
    ORDER BY m.ORDEN, sm.ORDEN;
END;
GO
