-- SP_ACTUALIZAR_SUBMENU
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_SUBMENU
    @ID_SUBMENU INT,
    @NOMBRE VARCHAR(50),
    @ICONO VARCHAR(50),
    @URL VARCHAR(100)
AS
BEGIN
    UPDATE MAE_SUBMENU
    SET NOMBRE = @NOMBRE,
        ICONO = @ICONO,
        URL = @URL
    WHERE ID_SUBMENU = @ID_SUBMENU AND ESTADO = 1;
END;
GO